version: "3.8"

services:
  postgres:
    container_name: school-mgmt-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_mgmt
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../seed_db:/docker-entrypoint-initdb.d
    entrypoint:
      [
        "bash",
        "-c",
        "docker-entrypoint.sh postgres & sleep 10 && psql -U postgres -d school_mgmt -c 'DROP SCHEMA public CASCADE; CREATE SCHEMA public;' && psql -U postgres -d school_mgmt -f /docker-entrypoint-initdb.d/tables.sql && psql -U postgres -d school_mgmt -f /docker-entrypoint-initdb.d/seed-db.sql && wait",
      ]

volumes:
  pg_data:
